server:
  port: 8080
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    enabled: true
    changeLog: classpath:db/changelog/db.changelog-tenant.yaml
multitenancy:
  master:
    datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: password
      hikari:
        maximum-pool-size: 1
  tenant:
    datasource:
      url: ${multitenancy.master.datasource.url}
      username: postgres
      password: password